// Fieldwork OS: relatórios devem converter sinal em decisão, não apenas repetir números em cartões.
import Link from 'next/link'
import { ArrowUpRight, BarChart3, CheckCircle2, ClipboardCheck, Clock3, TrendingUp } from 'lucide-react'
import { getReportsData } from '@/src/app/actions/metrics'

const formatCurrency = (value: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 }).format(value)

export default async function ReportsPage() {
  const reports = await getReportsData()
  if (!reports) return <div className="fieldwork-panel p-8 text-sm text-[var(--coral)]">Não foi possível carregar os relatórios deste workspace.</div>
  const maxStepValue = Math.max(...reports.leadsByStep.map((step) => step.value), 1)
  const conversionRate = reports.wonCount + reports.lostCount > 0 ? Math.round((reports.wonCount / (reports.wonCount + reports.lostCount)) * 100) : 0

  return <div className="mx-auto w-full max-w-[1480px]"><div className="fieldwork-page-intro"><div><p className="fieldwork-page-kicker">06 / Inteligência comercial</p><h1 className="fieldwork-page-title">Leia o negócio<br /><em className="not-italic text-[var(--brand-primary)]">antes de decidir.</em></h1><p className="fieldwork-page-copy">O valor está distribuído onde? A equipa está a acompanhar o ritmo? Esta leitura responde antes da próxima reunião.</p></div><Link href="/dashboard/tasks" className="fieldwork-primary-button">Abrir cadência <ArrowUpRight size={14} /></Link></div>
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="fieldwork-metric" style={{ '--metric-color': 'var(--brand-primary)' } as React.CSSProperties}><div className="flex items-start justify-between"><span className="fieldwork-metric-label">Pipeline aberto</span><TrendingUp size={16} className="text-[var(--brand-primary)]" /></div><div className="fieldwork-metric-value">{formatCurrency(reports.totalPipeline)}</div><p className="fieldwork-metric-note">{reports.totalLeads} leads no workspace</p></div><div className="fieldwork-metric" style={{ '--metric-color': 'var(--moss)' } as React.CSSProperties}><div className="flex items-start justify-between"><span className="fieldwork-metric-label">Vendas ganhas</span><CheckCircle2 size={16} className="text-[var(--moss)]" /></div><div className="fieldwork-metric-value">{formatCurrency(reports.totalWon)}</div><p className="fieldwork-metric-note text-[var(--moss)]">{reports.wonCount} negócios convertidos</p></div><div className="fieldwork-metric" style={{ '--metric-color': 'var(--lilac)' } as React.CSSProperties}><div className="flex items-start justify-between"><span className="fieldwork-metric-label">Conversão</span><BarChart3 size={16} className="text-[var(--lilac)]" /></div><div className="fieldwork-metric-value">{conversionRate}%</div><p className="fieldwork-metric-note">Ganhos sobre fechados</p></div><div className="fieldwork-metric" style={{ '--metric-color': 'var(--coral)' } as React.CSSProperties}><div className="flex items-start justify-between"><span className="fieldwork-metric-label">Follow-ups abertos</span><ClipboardCheck size={16} className="text-[var(--coral)]" /></div><div className="fieldwork-metric-value">{reports.openTasks}</div><p className="fieldwork-metric-note text-[var(--coral)]">{reports.overdueTasks} em atraso</p></div></div>
    <div className="mt-5 grid grid-cols-1 gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="fieldwork-panel p-6 md:p-8"><div className="mb-8 flex items-start justify-between"><div><p className="fieldwork-page-kicker">Distribuição do pipeline</p><h2 className="text-2xl font-black tracking-[-.04em] text-[var(--ink)]">Onde o valor está concentrado.</h2></div><span className="fieldwork-report-stamp">DADOS DO WORKSPACE</span></div>{reports.leadsByStep.length === 0 ? <div className="fieldwork-empty-timeline">Ainda não há leads suficientes para desenhar a distribuição.</div> : <div className="space-y-6">{reports.leadsByStep.map((step, index) => <div key={step.title}><div className="mb-2 flex items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="fieldwork-pipeline-column-index">0{index + 1}</span><span className="text-xs font-black text-[var(--ink)]">{step.title}</span></div><span className="font-mono text-[10px] font-bold text-[var(--ink-soft)]">{formatCurrency(step.value)} · {step.count}</span></div><div className="fieldwork-report-bar"><i style={{ width: `${Math.max((step.value / maxStepValue) * 100, step.value > 0 ? 5 : 0)}%`, backgroundColor: step.color }} /></div></div>)}</div>}</section><section className="fieldwork-panel overflow-hidden bg-[var(--ink)] p-6 text-white md:p-8"><p className="fieldwork-page-kicker !text-[#8fa8ff]">Saúde da operação</p><h2 className="mt-1 text-2xl font-black tracking-[-.04em]">O ritmo de execução.</h2><div className="mt-9 space-y-5"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div className="flex items-center gap-3 text-sm text-[#b5c0c5]"><Clock3 size={17} className="text-[var(--coral)]" /> Em atraso</div><strong className="font-serif text-3xl text-[var(--coral)]">{reports.overdueTasks}</strong></div><div className="flex items-center justify-between border-b border-white/10 pb-5"><div className="flex items-center gap-3 text-sm text-[#b5c0c5]"><ClipboardCheck size={17} className="text-[#8fa8ff]" /> Em aberto</div><strong className="font-serif text-3xl">{reports.openTasks}</strong></div><div className="flex items-center justify-between"><div className="flex items-center gap-3 text-sm text-[#b5c0c5]"><CheckCircle2 size={17} className="text-[var(--moss)]" /> Concluídas</div><strong className="font-serif text-3xl text-[var(--moss)]">{reports.completedTasks}</strong></div></div><div className="mt-10 border-t border-white/10 pt-5 text-xs leading-5 text-[#a8b3b8]">Tarefas em atraso são sinal de que o pipeline perdeu o próximo passo. Comece por limpar a fila, não por abrir mais oportunidades.</div></section></div>
  </div>
}
