import Link from 'next/link'
import { ArrowLeft, ArrowRight, KeyRound } from 'lucide-react'
import { login } from '@/src/app/actions/auth'
import GoogleLoginButton from '@/src/components/GoogleLoginButton'

// Fieldwork OS: autenticação como uma porta de entrada calma, com hierarquia e sem ruído.
export default function LoginPage({ searchParams }: { searchParams: { error?: string; message?: string } }) {
  return <div className="fieldwork-auth-shell"><div className="fieldwork-auth-aside"><Link href="/" className="fieldwork-wordmark"><span className="fieldwork-wordmark-mark">ƒ</span><span>fieldwork<span className="text-[var(--coral)]">.</span></span></Link><div><p className="fieldwork-page-kicker">A operação continua</p><h1>Volte para<br /><em>o ritmo.</em></h1><p>Os seus leads, conversas e próximos movimentos esperam no mesmo lugar.</p></div><span className="fieldwork-auth-aside-note">FIELDWORK OS / 2026</span></div><main className="fieldwork-auth-main"><div className="fieldwork-auth-card"><Link href="/" className="fieldwork-auth-back"><ArrowLeft size={14} /> Voltar ao início</Link><div className="mb-8 mt-10"><span className="fieldwork-auth-icon"><KeyRound size={18} /></span><p className="fieldwork-page-kicker mt-7">Acesso ao workspace</p><h2>Bem-vindo de volta.</h2><p>Entre para continuar a transformar contexto em próximo passo.</p></div><GoogleLoginButton /><div className="fieldwork-auth-divider"><span>ou entrar com e-mail</span></div><form action={login} className="space-y-4"><div><label className="fieldwork-form-label" htmlFor="login-email">E-mail</label><input id="login-email" name="email" type="email" required className="fieldwork-form-input" placeholder="voce@empresa.com" /></div><div><label className="fieldwork-form-label" htmlFor="login-password">Senha</label><input id="login-password" name="password" type="password" required className="fieldwork-form-input" placeholder="A sua senha" /></div>{(searchParams?.error || searchParams?.message) && <div className="fieldwork-auth-error">{searchParams.error || searchParams.message}</div>}<button type="submit" className="fieldwork-primary-button w-full justify-center">Entrar no workspace <ArrowRight size={15} /></button></form><p className="fieldwork-auth-switch">Ainda não tem workspace? <Link href="/signup">Criar gratuitamente</Link></p></div></main></div>
}
