'use client'

import { Pencil, UsersRound, X } from 'lucide-react'
import { useState } from 'react'
import { updateEmployee } from '@/src/app/actions/team'
import ModalPortal from '@/src/components/ModalPortal'

type Member = { id: string; full_name: string; role: string; workspace_role?: string }

// Fieldwork OS: permissões são contexto de trabalho, não um formulário administrativo comprimido.
export default function EditEmployeeModal({ member }: { member: Member }) {
  const [isOpen, setIsOpen] = useState(false); const [loading, setLoading] = useState(false); const [errorMsg, setErrorMsg] = useState('')
  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setErrorMsg(''); const response = await updateEmployee(new FormData(event.currentTarget)); setLoading(false); if (response.success) { setIsOpen(false); window.location.reload() } else setErrorMsg(response.error || 'Erro ao atualizar membro') }
  return <><button type="button" onClick={() => setIsOpen(true)} className="fieldwork-inline-edit"><Pencil size={13} /> Editar</button>{isOpen && <ModalPortal><div className="fieldwork-modal-backdrop" onClick={() => setIsOpen(false)}><div className="fieldwork-modal-card max-w-md" onClick={(event) => event.stopPropagation()}><header className="fieldwork-modal-header"><div><p className="fieldwork-page-kicker">Acesso ao workspace</p><h2>Editar membro.</h2><p><UsersRound size={13} className="mr-1 inline" /> {member.full_name}</p></div><button type="button" onClick={() => setIsOpen(false)} className="fieldwork-modal-close" aria-label="Fechar"><X size={17} /></button></header><form onSubmit={handleSubmit} className="fieldwork-modal-form"><input type="hidden" name="employeeId" value={member.id} /><div><label className="fieldwork-form-label" htmlFor={`member-name-${member.id}`}>Nome completo</label><input id={`member-name-${member.id}`} name="fullName" type="text" defaultValue={member.full_name} required className="fieldwork-form-input" /></div><div><label className="fieldwork-form-label" htmlFor={`member-role-${member.id}`}>Função e permissão</label><select id={`member-role-${member.id}`} name="role" defaultValue={member.workspace_role || member.role} className="fieldwork-form-input"><option value="sales">Vendedor — gere os próprios negócios</option><option value="manager">Gestor — acompanha a equipa</option><option value="viewer">Visualizador — apenas leitura</option><option value="admin">Administrador — gere o workspace</option></select></div><div><label className="fieldwork-form-label" htmlFor={`member-password-${member.id}`}>Nova senha</label><input id={`member-password-${member.id}`} name="newPassword" type="password" placeholder="Deixe em branco para não alterar" className="fieldwork-form-input" /><p className="fieldwork-form-hint">Preencha apenas se precisar redefinir a senha de acesso.</p></div>{errorMsg && <div className="fieldwork-auth-error">{errorMsg}</div>}<footer className="fieldwork-modal-actions"><button type="button" onClick={() => setIsOpen(false)} className="fieldwork-secondary-button">Cancelar</button><button type="submit" disabled={loading} className="fieldwork-primary-button disabled:opacity-50">{loading ? 'A guardar...' : 'Guardar alterações'}</button></footer></form></div></div></ModalPortal>}</>
}
