'use client'

import { CalendarPlus, Clock3, FilePlus2, X } from 'lucide-react'
import { useState } from 'react'
import { addQuickNote } from '@/src/app/actions/kanban'
import ModalPortal from '@/src/components/ModalPortal'

type Lead = { id: string; name: string; observation?: string | null }

// Fieldwork OS: uma nota rápida deve preservar memória e, quando necessário, transformá-la numa data concreta.
export default function QuickNoteModal({ lead }: { lead: Lead }) {
  const [isOpen, setIsOpen] = useState(false); const [loading, setLoading] = useState(false); const [schedule, setSchedule] = useState(false); const [date, setDate] = useState(''); const [time, setTime] = useState('')
  const setTomorrow = () => { const tomorrow = new Date(); tomorrow.setDate(tomorrow.getDate() + 1); setDate(tomorrow.toISOString().split('T')[0]); setTime('10:00'); setSchedule(true) }
  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); const formData = new FormData(event.currentTarget); if (!schedule) { formData.delete('scheduleDate'); formData.delete('scheduleTime') }; const response = await addQuickNote(formData); setLoading(false); if (response.success) { setIsOpen(false); window.location.reload() } }
  return <><button type="button" onClick={(event) => { event.stopPropagation(); setIsOpen(true) }} className="fieldwork-inline-edit"><FilePlus2 size={13} /> Nota</button>{isOpen && <ModalPortal><div className="fieldwork-modal-backdrop" onClick={() => setIsOpen(false)}><div className="fieldwork-modal-card max-w-md" onClick={(event) => event.stopPropagation()}><header className="fieldwork-modal-header"><div><p className="fieldwork-page-kicker">Memória do relacionamento</p><h2>Adicionar nota.</h2><p>{lead.name}</p></div><button type="button" onClick={() => setIsOpen(false)} className="fieldwork-modal-close" aria-label="Fechar"><X size={17} /></button></header><form onSubmit={handleSubmit} className="fieldwork-modal-form"><input type="hidden" name="leadId" value={lead.id} /><div><label className="fieldwork-form-label" htmlFor={`quick-note-${lead.id}`}>O que precisa de ser lembrado?</label><textarea id={`quick-note-${lead.id}`} name="observation" rows={4} required defaultValue={lead.observation || ''} placeholder="Ex.: Cliente pediu contacto depois das 18h..." className="fieldwork-form-input min-h-[120px] resize-none" /></div><button type="button" onClick={setTomorrow} className="fieldwork-secondary-button self-start"><CalendarPlus size={14} /> Agendar para amanhã</button><div className="fieldwork-schedule-box"><label className="fieldwork-schedule-toggle"><input type="checkbox" checked={schedule} onChange={(event) => setSchedule(event.target.checked)} /><span>Salvar também na agenda</span></label>{schedule && <div className="grid grid-cols-1 gap-3 border-t border-[var(--line)] pt-4 sm:grid-cols-2"><div><label className="fieldwork-form-label" htmlFor={`quick-note-date-${lead.id}`}>Data</label><input id={`quick-note-date-${lead.id}`} name="scheduleDate" type="date" required={schedule} value={date} onChange={(event) => setDate(event.target.value)} className="fieldwork-form-input" /></div><div><label className="fieldwork-form-label" htmlFor={`quick-note-time-${lead.id}`}>Hora</label><input id={`quick-note-time-${lead.id}`} name="scheduleTime" type="time" required={schedule} value={time} onChange={(event) => setTime(event.target.value)} className="fieldwork-form-input" /></div></div>}</div><footer className="fieldwork-modal-actions"><span className="mr-auto inline-flex items-center gap-1.5 self-center text-[10px] text-[var(--ink-faint)]"><Clock3 size={13} /> Contexto guardado no lead</span><button type="button" onClick={() => setIsOpen(false)} className="fieldwork-secondary-button">Cancelar</button><button type="submit" disabled={loading} className="fieldwork-primary-button disabled:opacity-50">{loading ? 'A guardar...' : 'Guardar nota'}</button></footer></form></div></div></ModalPortal>}</>
}
