import Link from 'next/link'
import { ArrowUpRight, ContactRound, Filter, Search, SlidersHorizontal } from 'lucide-react'
import { getAllLeadsData } from '@/src/app/actions/kanban'
import EditLeadModal from '@/src/components/EditLeadModal'
import type { Lead } from '@/src/types/crm'

// Fieldwork OS: uma base de contactos deve favorecer decisão e contexto, não obrigar a equipa a decifrar microtexto.
export default async function LeadsPage({ searchParams }: { searchParams: { search?: string; interest?: string; stepId?: string } }) {
  const search = searchParams.search || ''
  const interest = searchParams.interest || ''
  const stepFilter = searchParams.stepId || 'all'
  const { leads, steps, members, userRole, customFields } = await getAllLeadsData()
  let filteredLeads = leads || []
  if (search) filteredLeads = filteredLeads.filter((lead) => lead.name.toLowerCase().includes(search.toLowerCase()) || Boolean(lead.phone?.includes(search)) || Boolean(lead.email?.toLowerCase().includes(search.toLowerCase())))
  if (interest) filteredLeads = filteredLeads.filter((lead) => lead.custom_data && Object.values(lead.custom_data).some((value) => String(value).toLowerCase().includes(interest.toLowerCase())))
  if (stepFilter !== 'all') filteredLeads = filteredLeads.filter((lead) => lead.step_id === stepFilter)

  return <div className="mx-auto w-full max-w-[1480px]">
    <div className="fieldwork-page-intro"><div><p className="fieldwork-page-kicker">05 / Base de relacionamento</p><h1 className="fieldwork-page-title">Contactos que<br /><em className="not-italic text-[var(--brand-primary)]">merecem contexto.</em></h1><p className="fieldwork-page-copy">Encontre pessoas, negócios e sinais do processo. Quando o contexto estiver pronto, abra o detalhe e defina o próximo movimento.</p></div><div className="flex flex-wrap gap-2"><Link href="/dashboard/leads/importar" className="fieldwork-secondary-button">Importar CSV</Link><Link href="/dashboard/leads/export" className="fieldwork-secondary-button">Exportar CSV</Link></div></div>
    <div className="mb-5 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="fieldwork-metric" style={{ '--metric-color': 'var(--brand-primary)' } as React.CSSProperties}><span className="fieldwork-metric-label">Base filtrada</span><div className="fieldwork-metric-value">{filteredLeads.length}</div><p className="fieldwork-metric-note">de {leads?.length || 0} contactos ativos</p></div><div className="fieldwork-metric" style={{ '--metric-color': 'var(--moss)' } as React.CSSProperties}><span className="fieldwork-metric-label">Com e-mail</span><div className="fieldwork-metric-value">{filteredLeads.filter((lead) => lead.email).length}</div><p className="fieldwork-metric-note text-[var(--moss)]">Prontos para contacto</p></div><div className="fieldwork-metric" style={{ '--metric-color': 'var(--lilac)' } as React.CSSProperties}><span className="fieldwork-metric-label">Com valor</span><div className="fieldwork-metric-value">{filteredLeads.filter((lead) => Number(lead.lead_value || 0) > 0).length}</div><p className="fieldwork-metric-note">Oportunidades qualificadas</p></div><div className="fieldwork-metric" style={{ '--metric-color': 'var(--coral)' } as React.CSSProperties}><span className="fieldwork-metric-label">Etapas ativas</span><div className="fieldwork-metric-value">{steps.length}</div><p className="fieldwork-metric-note">Vocabulário do pipeline</p></div></div>
    <section className="fieldwork-filter-bar fieldwork-panel mb-5"><div className="mb-4 flex items-center gap-2"><Filter size={15} className="text-[var(--brand-primary)]" /><span className="fieldwork-form-label !mb-0">Filtrar a base</span><span className="ml-auto fieldwork-filter-count">{filteredLeads.length} resultados</span></div><form method="GET" action="/dashboard/leads" className="grid grid-cols-1 items-end gap-4 md:grid-cols-[1.2fr_1fr_.8fr_auto]"><div><label className="fieldwork-form-label" htmlFor="lead-search">Nome, e-mail ou telefone</label><div className="relative"><Search size={15} className="absolute left-3 top-3.5 text-[var(--ink-faint)]" /><input id="lead-search" name="search" type="text" defaultValue={search} placeholder="Pesquisar contacto..." className="fieldwork-form-input pl-10" /></div></div><div><label className="fieldwork-form-label" htmlFor="lead-interest">Sinal ou interesse</label><input id="lead-interest" name="interest" type="text" defaultValue={interest} placeholder="Ex.: plano anual" className="fieldwork-form-input" /></div><div><label className="fieldwork-form-label" htmlFor="lead-step">Etapa do pipeline</label><select id="lead-step" name="stepId" defaultValue={stepFilter} className="fieldwork-form-input"><option value="all">Todas as etapas</option>{steps.map((step) => <option key={step.id} value={step.id}>{step.title}</option>)}</select></div><div className="flex gap-2"><Link href="/dashboard/leads" className="fieldwork-secondary-button">Limpar</Link><button type="submit" className="fieldwork-primary-button"><SlidersHorizontal size={14} /> Filtrar</button></div></form></section>
    <section className="fieldwork-leads-table fieldwork-panel overflow-hidden"><header className="fieldwork-table-header"><div><p className="fieldwork-page-kicker !mb-1">Lista viva</p><h2>Relacionamentos em aberto</h2></div><Link href="/dashboard/kanban" className="fieldwork-inline-link">Ver no pipeline <ArrowUpRight size={14} /></Link></header><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr><th>Contacto / negócio</th><th>Etapa</th><th>Sinais</th><th>Entrada</th><th>Responsável</th><th /></tr></thead><tbody>{filteredLeads.length ? filteredLeads.map((lead: Lead) => { const profileData = Array.isArray(lead.profiles) ? lead.profiles[0] : lead.profiles; const step = steps.find((item) => item.id === lead.step_id); const customEntries = lead.custom_data ? Object.entries(lead.custom_data).filter(([, value]) => value) : []; return <tr key={lead.id} className="fieldwork-lead-row"><td><Link href={`/dashboard/leads/${lead.id}`} className="fieldwork-table-contact">{lead.name}</Link><span className="fieldwork-table-subtext">{lead.email || lead.phone || 'Sem contacto direto'}</span>{Number(lead.lead_value || 0) > 0 && <span className="fieldwork-table-value">R$ {Number(lead.lead_value).toFixed(0)}</span>}</td><td><span className="fieldwork-table-pill">{step?.title || 'Sem etapa'}</span></td><td><div className="fieldwork-table-signals">{customEntries.length ? customEntries.slice(0, 2).map(([key, value]) => <span key={key}>{customFields.find((field) => field.field_key === key)?.field_label || key}: {String(value)}</span>) : <span className="is-muted">Sem sinais adicionais</span>}</div></td><td className="fieldwork-table-date">{lead.created_at ? new Date(lead.created_at).toLocaleDateString('pt-BR') : '—'}</td><td><span className="fieldwork-table-owner">{profileData?.full_name || 'Não atribuído'}</span></td><td className="text-right"><EditLeadModal lead={lead} steps={steps} members={members} userRole={userRole} customFields={customFields} /></td></tr> }) : <tr><td colSpan={6}><div className="fieldwork-empty-leads"><ContactRound size={30} /><strong>Nenhum contacto encontrado.</strong><span>Ajuste os filtros ou importe uma base para começar a construir contexto.</span></div></td></tr>}</tbody></table></div></section>
  </div>
}
