import Link from 'next/link'
import { ArrowLeft, ArrowRight, Compass, Sparkles } from 'lucide-react'
import { signup } from '@/src/app/actions/auth'
import GoogleLoginButton from '@/src/components/GoogleLoginButton'

// Fieldwork OS: o cadastro apresenta a criação do workspace como uma decisão de operação, não como um formulário genérico.
export default function SignupPage({ searchParams }: { searchParams: { error?: string; message?: string } }) {
  return <div className="fieldwork-auth-shell"><div className="fieldwork-auth-aside is-signup"><Link href="/" className="fieldwork-wordmark"><span className="fieldwork-wordmark-mark">ƒ</span><span>fieldwork<span className="text-[var(--coral)]">.</span></span></Link><div><p className="fieldwork-page-kicker">Primeiro passo</p><h1>Construa um<br /><em>workspace seu.</em></h1><p>Comece com a identidade da sua empresa. Depois, ajuste pipeline, equipa, campos e linguagem à medida que a operação cresce.</p><div className="fieldwork-auth-callout"><Sparkles size={16} /><span>O setup inicial já inclui pipeline, inbox, tarefas e relatórios.</span></div></div><span className="fieldwork-auth-aside-note">WHITE-LABEL BY DESIGN</span></div><main className="fieldwork-auth-main"><div className="fieldwork-auth-card"><Link href="/" className="fieldwork-auth-back"><ArrowLeft size={14} /> Voltar ao início</Link><div className="mb-7 mt-10"><span className="fieldwork-auth-icon is-coral"><Compass size={18} /></span><p className="fieldwork-page-kicker mt-7">Novo workspace</p><h2>Comece pela sua realidade.</h2><p>Uma conta. Uma base de trabalho. O seu jeito de vender.</p></div><GoogleLoginButton /><div className="fieldwork-auth-divider"><span>ou criar com e-mail</span></div><form action={signup} className="space-y-4"><div><label className="fieldwork-form-label" htmlFor="signup-company">Nome da empresa ou operação</label><input id="signup-company" name="companyName" type="text" required className="fieldwork-form-input" placeholder="Ex.: Estúdio Norte" /></div><div><label className="fieldwork-form-label" htmlFor="signup-name">O seu nome</label><input id="signup-name" name="fullName" type="text" required className="fieldwork-form-input" placeholder="Ex.: Joana Silva" /></div><div><label className="fieldwork-form-label" htmlFor="signup-email">E-mail de trabalho</label><input id="signup-email" name="email" type="email" required className="fieldwork-form-input" placeholder="voce@empresa.com" /></div><div><label className="fieldwork-form-label" htmlFor="signup-password">Criar senha</label><input id="signup-password" name="password" type="password" required className="fieldwork-form-input" placeholder="Mínimo de 6 caracteres" /></div>{(searchParams?.error || searchParams?.message) && <div className="fieldwork-auth-error">{searchParams.error || searchParams.message}</div>}<button type="submit" className="fieldwork-primary-button w-full justify-center">Criar meu workspace <ArrowRight size={15} /></button></form><p className="fieldwork-auth-switch">Já tem uma conta? <Link href="/login">Entrar no workspace</Link></p></div></main></div>
}
